# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e2ce56bb45559f5b995c5590559237043ba2b7c74d4703ab1c731a49227406d6cd6bf96162c924b11ef44f432113385e603642d37b306cd14bda3df87382fb3b

test:
  secret_key_base: 22d976a91ca074ab4bd8e479130433e66bdded0bfa4cea154d8ff52cd78f490ae2c7c96a730044b7bf6df6e5d320248c99d0f212bc192ca31d72caa242a55c34

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
